const sports=[
{name:'Pallavolo',category:'Sport di squadra',description:'Palleggio, bagher e gioco di squadra. Un venerdì per trovare il ritmo, un punto alla volta.',image:'https://images.unsplash.com/photo-1728971121667-80d6513f83e1?auto=format&fit=crop&w=1200&q=85',alt:'Giocatori impegnati in una partita di pallavolo in palestra'},
{name:'Basket',category:'Sport di squadra',description:'Palleggio, passaggi e tiri a canestro. Alleniamo la coordinazione e impariamo a giocare insieme.',image:'https://images.unsplash.com/photo-1678032493201-ed4764b7d6f8?auto=format&fit=crop&w=1200&q=85',alt:'Pallone da basket su un campo da pallacanestro'},
{name:'Calcio',category:'Sport di squadra',description:'Controllo di palla, passaggi e una partita insieme. Spazio al movimento e alla collaborazione.',image:'https://images.unsplash.com/photo-1660926655800-3d11219f390d?auto=format&fit=crop&w=1200&q=85',alt:'Pallone da calcio sul prato'},
{name:'Badminton',category:'Sport con racchetta',description:'Servizio, scambi e precisione. Mettiamo alla prova i riflessi e il controllo dei movimenti.',image:'https://images.unsplash.com/photo-1564226803380-91139fdcb4d0?auto=format&fit=crop&w=1200&q=85',alt:'Volano bianco per il badminton'}];
const closures={'2026-12-25':'Vacanze di Natale','2027-01-01':'Vacanze di Natale','2027-03-26':'Vacanze di Pasqua','2027-04-30':'Ponte del 1° maggio'};
const lessons=[];for(let d=new Date('2026-09-11T12:00:00Z');d<=new Date('2027-06-08T12:00:00Z');d.setUTCDate(d.getUTCDate()+7)){const date=d.toISOString().slice(0,10);if(!closures[date])lessons.push({date,sport:0,skip:false})}
let saved={};let storageAvailable=true;try{saved=JSON.parse(localStorage.getItem('venerdi-2026-27')||'{}')}catch{storageAvailable=false}for(const l of lessons){const v=saved?.[l.date];if(v&&Number.isInteger(v.sport)&&sports[v.sport]){l.sport=v.sport;l.skip=v.skip===true}}
const $=id=>document.getElementById(id);const format=(date,options)=>new Intl.DateTimeFormat('it-IT',{timeZone:'Europe/Rome',...options}).format(new Date(date+'T12:00:00Z'));
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
let showAll=false,editing=null,current=null;
function render(){const now=today();current=lessons.find(l=>l.date>=now&&!l.skip)||null;const display=current;const finished=!display;const s=display?sports[display.sport]:sports[0];$('week-status').textContent=finished?'Anno concluso':display.date===now?'Oggi in palestra':'Prossimo venerdì';$('hero-date').textContent=display?format(display.date,{day:'numeric',month:'long',year:'numeric'}):'8 giugno 2027';$('activity').textContent=finished?'Ci vediamo presto.':s.name;$('description').textContent=finished?'Il programma di quest’anno è terminato. Tutte le lezioni restano nel calendario.':s.description;$('category').textContent=finished?'Anno scolastico 2026–27':s.category;$('sport-image').src=s.image;$('sport-image').alt=s.alt;$('image-caption').textContent=finished?'Educazione fisica · 2026–27':s.name+' · In movimento';$('edit-current').hidden=finished;
const visible=lessons.filter(l=>showAll||l.date>=now);$('count').textContent=visible.filter(l=>!l.skip).length+' venerdì di attività';$('calendar').replaceChildren();let month='';let grid;for(const l of visible){if(l.date.slice(0,7)!==month){month=l.date.slice(0,7);const heading=document.createElement('h3');heading.className='month-title';heading.textContent=format(l.date,{month:'long'})+' '+l.date.slice(0,4);$('calendar').append(heading);grid=document.createElement('div');grid.className='lesson-grid';$('calendar').append(grid)}const button=document.createElement('button');button.className='lesson'+(l===current?' current':'')+(l.skip?' skipped':'');button.setAttribute('aria-label',format(l.date,{day:'numeric',month:'long',year:'numeric'})+': '+(l.skip?'Nessuna lezione':sports[l.sport].name)+'. Modifica attività');button.innerHTML='<span class="lesson-top"><span class="lesson-date">'+Number(l.date.slice(8))+'<small>VEN</small></span>'+(l===current?'<span class="lesson-tag">'+(l.date===now?'Oggi':'Prossima')+'</span>':'')+'</span><span class="lesson-name">'+(l.skip?'Nessuna lezione':sports[l.sport].name)+'</span><span class="lesson-category">'+(l.skip?'Chiusura della scuola':sports[l.sport].category)+'</span>';button.addEventListener('click',()=>openEditor(l));grid.append(button)}if(!visible.length){const p=document.createElement('p');p.textContent='Nessuna lezione in arrivo. Apri “Tutto l’anno” per rivedere il programma.';$('calendar').append(p)}$('upcoming').classList.toggle('active',!showAll);$('all').classList.toggle('active',showAll);$('upcoming').setAttribute('aria-pressed',String(!showAll));$('all').setAttribute('aria-pressed',String(showAll))}
function openEditor(l){editing=l;$('edit-date').textContent=format(l.date,{weekday:'long',day:'numeric',month:'long'});$('sport-select').value=l.sport;$('skip').checked=l.skip;$('sport-select').disabled=l.skip;$('editor').showModal()}
sports.forEach((s,i)=>{const option=document.createElement('option');option.value=i;option.textContent=s.name;$('sport-select').append(option)});$('skip').addEventListener('change',()=>{$('sport-select').disabled=$('skip').checked});$('edit-current').addEventListener('click',()=>current&&openEditor(current));$('close').addEventListener('click',()=>$('editor').close());$('upcoming').addEventListener('click',()=>{showAll=false;render()});$('all').addEventListener('click',()=>{showAll=true;render()});$('edit-form').addEventListener('submit',e=>{e.preventDefault();editing.sport=Number($('sport-select').value);editing.skip=$('skip').checked;saved[editing.date]={sport:editing.sport,skip:editing.skip};try{localStorage.setItem('venerdi-2026-27',JSON.stringify(saved));storageAvailable=true}catch{storageAvailable=false}$('editor').close();render();$('toast').textContent=storageAvailable?'Lezione salvata in questo browser':'Modifica applicata. Il browser non consente il salvataggio.';$('toast').style.display='block';setTimeout(()=>{$('toast').style.display='none'},4000)});render();setInterval(render,60000);
